In [1]:
# Binerizer 
# Binning  # Discritization

In [2]:
import numpy as np
import pandas as pd
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import *

In [3]:
df = pd.read_csv("../../Data/job_salary_prediction_dataset.csv")

In [4]:
X =  df.drop('salary', axis=1)
y = df['salary']

In [5]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [6]:
# 0-1 thershold = 2.5
binn = Binarizer(threshold=1)
# df['certifications'].unique()

In [7]:
binn.fit_transform(X_train[['certifications']])

array([[1],
       [0],
       [0],
       ...,
       [0],
       [1],
       [1]], shape=(200000, 1))

In [8]:
binn.transform(X_test[['certifications']])

array([[1],
       [0],
       [1],
       ...,
       [1],
       [0],
       [0]], shape=(50000, 1))

In [9]:
# Binning 
pd.cut(df['certifications'], 4)

0            (1.25, 2.5]
1         (-0.005, 1.25]
2         (-0.005, 1.25]
3         (-0.005, 1.25]
4         (-0.005, 1.25]
               ...
249995    (-0.005, 1.25]
249996       (1.25, 2.5]
249997    (-0.005, 1.25]
249998       (3.75, 5.0]
249999       (3.75, 5.0]
Name: certifications, Length: 250000, dtype: category
Categories (4, interval[float64, right]): [(-0.005, 1.25] < (1.25, 2.5] < (2.5, 3.75] < (3.75, 5.0]]

In [10]:
obj = KBinsDiscretizer(n_bins=4, encode='ordinal')

In [11]:
obj.fit_transform(X_train[['certifications']])

E:\class_repos\DataScience_evening\.venv\Lib\site-packages\sklearn\preprocessing\_discretization.py:304: FutureWarning: The current default behavior, quantile_method='linear', will be changed to quantile_method='averaged_inverted_cdf' in scikit-learn version 1.9 to naturally support sample weight equivalence properties by default. Pass quantile_method='averaged_inverted_cdf' explicitly to silence this warning.
  warnings.warn(

array([[3.],
       [1.],
       [1.],
       ...,
       [0.],
       [2.],
       [2.]], shape=(200000, 1))

In [12]:
obj.encode

'ordinal'

In [13]:
obj.bin_edges_

array([array([0., 1., 2., 4., 5.])], dtype=object)

In [14]:
df

,job_title,experience_years,education_level,skills_count,industry,company_size,location,remote_work,certifications,salary
0,AI Engineer,10,Bachelor,2,Healthcare,Medium,India,Hybrid,2,109413
1,Data Analyst,5,Bachelor,17,Telecom,Small,Australia,No,0,93764
2,Frontend Developer,18,PhD,4,Media,Medium,Singapore,No,1,148123
3,Business Analyst,19,PhD,13,Retail,Medium,Canada,Yes,0,189123
4,Product Manager,15,Bachelor,7,Manufacturing,Large,Sweden,Yes,0,165069
...,...,...,...,...,...,...,...,...,...,...
249995,Software Engineer,17,PhD,2,Telecom,Enterprise,India,No,1,127791
249996,Frontend Developer,20,PhD,7,Telecom,Startup,Remote,No,2,154593
249997,Business Analyst,1,Bachelor,12,Retail,Enterprise,India,Yes,0,75988
249998,Data Scientist,0,High School,2,Consulting,Small,Sweden,Hybrid,5,90467
249999,Data Analyst,16,Diploma,2,Technology,Medium,UK,No,5,133084

In [15]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 250000 entries, 0 to 249999
Data columns (total 10 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   job_title         250000 non-null  str
 1   experience_years  250000 non-null  int64
 2   education_level   250000 non-null  str
 3   skills_count      250000 non-null  int64
 4   industry          250000 non-null  str
 5   company_size      250000 non-null  str
 6   location          250000 non-null  str
 7   remote_work       250000 non-null  str
 8   certifications    250000 non-null  int64
 9   salary            250000 non-null  int64
dtypes: int64(4), str(6)
memory usage: 30.7 MB

In [16]:
numeric = df.select_dtypes('number')
text = df.select_dtypes(exclude = 'number')

In [17]:
numeric.shape, text.shape

((250000, 4), (250000, 6))

In [18]:
text

,job_title,education_level,industry,company_size,location,remote_work
0,AI Engineer,Bachelor,Healthcare,Medium,India,Hybrid
1,Data Analyst,Bachelor,Telecom,Small,Australia,No
2,Frontend Developer,PhD,Media,Medium,Singapore,No
3,Business Analyst,PhD,Retail,Medium,Canada,Yes
4,Product Manager,Bachelor,Manufacturing,Large,Sweden,Yes
...,...,...,...,...,...,...
249995,Software Engineer,PhD,Telecom,Enterprise,India,No
249996,Frontend Developer,PhD,Telecom,Startup,Remote,No
249997,Business Analyst,Bachelor,Retail,Enterprise,India,Yes
249998,Data Scientist,High School,Consulting,Small,Sweden,Hybrid
249999,Data Analyst,Diploma,Technology,Medium,UK,No

In [19]:
numeric

        experience_years  skills_count  certifications  salary
0                     10             2               2  109413
1                      5            17               0   93764
2                     18             4               1  148123
3                     19            13               0  189123
4                     15             7               0  165069
...                  ...           ...             ...     ...
249995                17             2               1  127791
249996                20             7               2  154593
249997                 1            12               0   75988
249998                 0             2               5   90467
249999                16             2               5  133084

[250000 rows x 4 columns]

In [20]:
numeric.describe()

       experience_years   skills_count  certifications         salary
count     250000.000000  250000.000000   250000.000000  250000.000000
mean          10.005408       9.997812        2.491928  145718.080524
std            6.060602       5.479288        1.706475   37407.952729
min            0.000000       1.000000        0.000000   31867.000000
25%            5.000000       5.000000        1.000000  119358.000000
50%           10.000000      10.000000        2.000000  143453.000000
75%           15.000000      15.000000        4.000000  169492.000000
max           20.000000      19.000000        5.000000  333046.000000

In [21]:
scale  = StandardScaler()
arr = scale.fit_transform(numeric)

In [22]:
numeric

        experience_years  skills_count  certifications  salary
0                     10             2               2  109413
1                      5            17               0   93764
2                     18             4               1  148123
3                     19            13               0  189123
4                     15             7               0  165069
...                  ...           ...             ...     ...
249995                17             2               1  127791
249996                20             7               2  154593
249997                 1            12               0   75988
249998                 0             2               5   90467
249999                16             2               5  133084

[250000 rows x 4 columns]

In [23]:
num_sc = pd.DataFrame(arr, columns=scale.get_feature_names_out())

In [24]:
num_sc

        experience_years  skills_count  certifications    salary
0              -0.000892     -1.459647       -0.288272 -0.970520
1              -0.825894      1.277940       -1.460281 -1.388854
2               1.319111     -1.094636       -0.874276  0.064289
3               1.484112      0.547917       -1.460281  1.160315
4               0.824110     -0.547118       -1.460281  0.517295
...                  ...           ...             ...       ...
249995          1.154111     -1.459647       -0.874276 -0.479233
249996          1.649112     -0.547118       -0.288272  0.237247
249997         -1.485896      0.365411       -1.460281 -1.864048
249998         -1.650897     -1.459647        1.469741 -1.476991
249999          0.989110     -1.459647        1.469741 -0.337738

[250000 rows x 4 columns]

In [25]:
text

,job_title,education_level,industry,company_size,location,remote_work
0,AI Engineer,Bachelor,Healthcare,Medium,India,Hybrid
1,Data Analyst,Bachelor,Telecom,Small,Australia,No
2,Frontend Developer,PhD,Media,Medium,Singapore,No
3,Business Analyst,PhD,Retail,Medium,Canada,Yes
4,Product Manager,Bachelor,Manufacturing,Large,Sweden,Yes
...,...,...,...,...,...,...
249995,Software Engineer,PhD,Telecom,Enterprise,India,No
249996,Frontend Developer,PhD,Telecom,Startup,Remote,No
249997,Business Analyst,Bachelor,Retail,Enterprise,India,Yes
249998,Data Scientist,High School,Consulting,Small,Sweden,Hybrid
249999,Data Analyst,Diploma,Technology,Medium,UK,No

In [26]:
text.nunique()

job_title          12
education_level     5
industry           10
company_size        5
location           10
remote_work         3
dtype: int64

In [27]:
12 + 10 + 10 + 3 + 2 + 4 - 4

37

In [28]:
job= text['job_title'].unique()

In [29]:
# 1-12  6
d = {}
for idx, title in enumerate(job, 1):
    d[title] = idx
    # print(idx, title)

In [30]:
# smart classroom management softwre for enhanced learn
text['job_title'] = text['job_title'].map(d)

In [31]:
text

,job_title,education_level,industry,company_size,location,remote_work
0,1,Bachelor,Healthcare,Medium,India,Hybrid
1,2,Bachelor,Telecom,Small,Australia,No
2,3,PhD,Media,Medium,Singapore,No
3,4,PhD,Retail,Medium,Canada,Yes
4,5,Bachelor,Manufacturing,Large,Sweden,Yes
...,...,...,...,...,...,...
249995,9,PhD,Telecom,Enterprise,India,No
249996,3,PhD,Telecom,Startup,Remote,No
249997,4,Bachelor,Retail,Enterprise,India,Yes
249998,11,High School,Consulting,Small,Sweden,Hybrid
249999,2,Diploma,Technology,Medium,UK,No

In [32]:
def map_vars(data, series):
    d = {title: idx for idx, title in enumerate(data[series].unique(), 1)} 
    data[series] = data[series].map(d)

In [33]:
map_vars(text, 'industry')
map_vars(text, 'job_title')
map_vars(text, 'location')

In [34]:
text

        job_title education_level  industry company_size  location remote_work
0               1        Bachelor         1       Medium         1      Hybrid
1               2        Bachelor         2        Small         2          No
2               3             PhD         3       Medium         3          No
3               4             PhD         4       Medium         4         Yes
4               5        Bachelor         5        Large         5         Yes
...           ...             ...       ...          ...       ...         ...
249995          9             PhD         2   Enterprise         1          No
249996          3             PhD         2      Startup         8          No
249997          4        Bachelor         4   Enterprise         1         Yes
249998         11     High School         9        Small         5      Hybrid
249999          2         Diploma         8       Medium        10          No

[250000 rows x 6 columns]

In [35]:
from sklearn.preprocessing import StandardScaler, OneHotEncoder, OrdinalEncoder

In [36]:
ordinal = OrdinalEncoder(dtype=np.int64)
order = ordinal.fit_transform(text[['education_level', 'company_size']])

In [37]:
order

array([[0, 2],
       [0, 3],
       [4, 2],
       ...,
       [0, 0],
       [2, 3],
       [1, 2]], shape=(250000, 2))

In [38]:
ordinal.categories_

[array(['Bachelor', 'Diploma', 'High School', 'Master', 'PhD'],
       dtype=object),
 array(['Enterprise', 'Large', 'Medium', 'Small', 'Startup'], dtype=object)]

In [39]:
text[['education_level', 'company_size']] = order

In [40]:
text

,job_title,education_level,industry,company_size,location,remote_work
0,1,0,1,2,1,Hybrid
1,2,0,2,3,2,No
2,3,4,3,2,3,No
3,4,4,4,2,4,Yes
4,5,0,5,1,5,Yes
...,...,...,...,...,...,...
249995,9,4,2,0,1,No
249996,3,4,2,4,8,No
249997,4,0,4,0,1,Yes
249998,11,2,9,3,5,Hybrid
249999,2,1,8,2,10,No

In [41]:
numeric

        experience_years  skills_count  certifications  salary
0                     10             2               2  109413
1                      5            17               0   93764
2                     18             4               1  148123
3                     19            13               0  189123
4                     15             7               0  165069
...                  ...           ...             ...     ...
249995                17             2               1  127791
249996                20             7               2  154593
249997                 1            12               0   75988
249998                 0             2               5   90467
249999                16             2               5  133084

[250000 rows x 4 columns]

In [46]:
ohe = OneHotEncoder(sparse_output=False, drop = 'first', dtype=np.int64)

In [47]:
one_hot = ohe.fit_transform(text[['remote_work']])

In [49]:
data = pd.DataFrame(one_hot, columns=ohe.get_feature_names_out())

In [50]:
data

        remote_work_No  remote_work_Yes
0                    0                0
1                    1                0
2                    1                0
3                    0                1
4                    0                1
...                ...              ...
249995               1                0
249996               1                0
249997               0                1
249998               0                0
249999               1                0

[250000 rows x 2 columns]

In [51]:
numeric.shape, text.shape, data.shape

((250000, 4), (250000, 6), (250000, 2))

In [53]:
merged = numeric.join([text, data])

In [54]:
scale = StandardScaler()

In [58]:
merged.drop(columns='remote_work', inplace=True)

In [59]:
scale.fit_transform(merged)

array([[-8.92322321e-04, -1.45964725e+00, -2.88271936e-01, ...,
        -1.56485277e+00, -7.08938274e-01, -7.04369913e-01],
       [-8.25894468e-01,  1.27794008e+00, -1.46028059e+00, ...,
        -1.21647164e+00,  1.41056004e+00, -7.04369913e-01],
       [ 1.31911111e+00, -1.09463561e+00, -8.74276261e-01, ...,
        -8.68090515e-01,  1.41056004e+00, -7.04369913e-01],
       ...,
       [-1.48589618e+00,  3.65410967e-01, -1.46028059e+00, ...,
        -1.56485277e+00, -7.08938274e-01,  1.41970857e+00],
       [-1.65089661e+00, -1.45964725e+00,  1.46974104e+00, ...,
        -1.71328263e-01, -7.08938274e-01, -7.04369913e-01],
       [ 9.89110253e-01, -1.45964725e+00,  1.46974104e+00, ...,
         1.57057736e+00,  1.41056004e+00, -7.04369913e-01]],
      shape=(250000, 11))

In [60]:
scale.get_feature_names_out()

array(['experience_years', 'skills_count', 'certifications', 'salary',
       'job_title', 'education_level', 'industry', 'company_size',
       'location', 'remote_work_No', 'remote_work_Yes'], dtype=object)