In [1]:
import pandas as pd
import numpy as np

In [73]:
df = pd.read_csv('../../Data/train.csv')

In [4]:
df['Age']

0      22.0
1      38.0
2      26.0
3      35.0
4      35.0
       ...
886    27.0
887    19.0
888     NaN
889    26.0
890    32.0
Name: Age, Length: 891, dtype: float64

In [6]:
# imputation 
from sklearn.impute import SimpleImputer

In [7]:
imputer = SimpleImputer(strategy='mean', 'median', 'most_frequent', 'constant')

In [8]:
imputer

SimpleImputer()

In [ ]:
# fit transform

In [12]:
imputer.fit(df[['Age']])

SimpleImputer()

In [15]:
imputer.transform(df[['Age']])

array([[22.        ],
       [38.        ],
       [26.        ],
       [35.        ],
       [35.        ],
       [29.69911765],
       [54.        ],
       [ 2.        ],
       [27.        ],
       [14.        ],
       [ 4.        ],
       [58.        ],
       [20.        ],
       [39.        ],
       [14.        ],
       [55.        ],
       [ 2.        ],
       [29.69911765],
       [31.        ],
       [29.69911765],
       [35.        ],
       [34.        ],
       [15.        ],
       [28.        ],
       [ 8.        ],
       [38.        ],
       [29.69911765],
       [19.        ],
       [29.69911765],
       [29.69911765],
       [40.        ],
       [29.69911765],
       [29.69911765],
       [66.        ],
       [28.        ],
       [42.        ],
       [29.69911765],
       [21.        ],
       [18.        ],
       [14.        ],
       [40.        ],
       [27.        ],
       [29.69911765],
       [ 3.        ],
       [19.        ],
       [29.69911765],
       [29.69911765],
       [29.69911765],
       [29.69911765],
       [18.        ],
       [ 7.        ],
       [21.        ],
       [49.        ],
       [29.        ],
       [65.        ],
       [29.69911765],
       [21.        ],
       [28.5       ],
       [ 5.        ],
       [11.        ],
       [22.        ],
       [38.        ],
       [45.        ],
       [ 4.        ],
       [29.69911765],
       [29.69911765],
       [29.        ],
       [19.        ],
       [17.        ],
       [26.        ],
       [32.        ],
       [16.        ],
       [21.        ],
       [26.        ],
       [32.        ],
       [25.        ],
       [29.69911765],
       [29.69911765],
       [ 0.83      ],
       [30.        ],
       [22.        ],
       [29.        ],
       [29.69911765],
       [28.        ],
       [17.        ],
       [33.        ],
       [16.        ],
       [29.69911765],
       [23.        ],
       [24.        ],
       [29.        ],
       [20.        ],
       [46.        ],
       [26.        ],
       [59.        ],
       [29.69911765],
       [71.        ],
       [23.        ],
       [34.        ],
       [34.        ],
       [28.        ],
       [29.69911765],
       [21.        ],
       [33.        ],
       [37.        ],
       [28.        ],
       [21.        ],
       [29.69911765],
       [38.        ],
       [29.69911765],
       [47.        ],
       [14.5       ],
       [22.        ],
       [20.        ],
       [17.        ],
       [21.        ],
       [70.5       ],
       [29.        ],
       [24.        ],
       [ 2.        ],
       [21.        ],
       [29.69911765],
       [32.5       ],
       [32.5       ],
       [54.        ],
       [12.        ],
       [29.69911765],
       [24.        ],
       [29.69911765],
       [45.        ],
       [33.        ],
       [20.        ],
       [47.        ],
       [29.        ],
       [25.        ],
       [23.        ],
       [19.        ],
       [37.        ],
       [16.        ],
       [24.        ],
       [29.69911765],
       [22.        ],
       [24.        ],
       [19.        ],
       [18.        ],
       [19.        ],
       [27.        ],
       [ 9.        ],
       [36.5       ],
       [42.        ],
       [51.        ],
       [22.        ],
       [55.5       ],
       [40.5       ],
       [29.69911765],
       [51.        ],
       [16.        ],
       [30.        ],
       [29.69911765],
       [29.69911765],
       [44.        ],
       [40.        ],
       [26.        ],
       [17.        ],
       [ 1.        ],
       [ 9.        ],
       [29.69911765],
       [45.        ],
       [29.69911765],
       [28.        ],
       [61.        ],
       [ 4.        ],
       [ 1.        ],
       [21.        ],
       [56.        ],
       [18.        ],
       [29.69911765],
       [50.        ],
       [30.        ],
       [36.        ],
       [29.69911765],
       [29.69911765],
       [ 9.        ],
       [ 1.        ],
       [ 4.        ],
       [29.69911765],
       [29.69911765],
       [45.        ],
       [40.        ],
       [36.        ],
       [32.        ],
       [19.        ],
       [19.        ],
       [ 3.        ],
       [44.        ],
       [58.        ],
       [29.69911765],
       [42.        ],
       [29.69911765],
       [24.        ],
       [28.        ],
       [29.69911765],
       [34.        ],
       [45.5       ],
       [18.        ],
       [ 2.        ],
       [32.        ],
       [26.        ],
       [16.        ],
       [40.        ],
       [24.        ],
       [35.        ],
       [22.        ],
       [30.        ],
       [29.69911765],
       [31.        ],
       [27.        ],
       [42.        ],
       [32.        ],
       [30.        ],
       [16.        ],
       [27.        ],
       [51.        ],
       [29.69911765],
       [38.        ],
       [22.        ],
       [19.        ],
       [20.5       ],
       [18.        ],
       [29.69911765],
       [35.        ],
       [29.        ],
       [59.        ],
       [ 5.        ],
       [24.        ],
       [29.69911765],
       [44.        ],
       [ 8.        ],
       [19.        ],
       [33.        ],
       [29.69911765],
       [29.69911765],
       [29.        ],
       [22.        ],
       [30.        ],
       [44.        ],
       [25.        ],
       [24.        ],
       [37.        ],
       [54.        ],
       [29.69911765],
       [29.        ],
       [62.        ],
       [30.        ],
       [41.        ],
       [29.        ],
       [29.69911765],
       [30.        ],
       [35.        ],
       [50.        ],
       [29.69911765],
       [ 3.        ],
       [52.        ],
       [40.        ],
       [29.69911765],
       [36.        ],
       [16.        ],
       [25.        ],
       [58.        ],
       [35.        ],
       [29.69911765],
       [25.        ],
       [41.        ],
       [37.        ],
       [29.69911765],
       [63.        ],
       [45.        ],
       [29.69911765],
       [ 7.        ],
       [35.        ],
       [65.        ],
       [28.        ],
       [16.        ],
       [19.        ],
       [29.69911765],
       [33.        ],
       [30.        ],
       [22.        ],
       [42.        ],
       [22.        ],
       [26.        ],
       [19.        ],
       [36.        ],
       [24.        ],
       [24.        ],
       [29.69911765],
       [23.5       ],
       [ 2.        ],
       [29.69911765],
       [50.        ],
       [29.69911765],
       [29.69911765],
       [19.        ],
       [29.69911765],
       [29.69911765],
       [ 0.92      ],
       [29.69911765],
       [17.        ],
       [30.        ],
       [30.        ],
       [24.        ],
       [18.        ],
       [26.        ],
       [28.        ],
       [43.        ],
       [26.        ],
       [24.        ],
       [54.        ],
       [31.        ],
       [40.        ],
       [22.        ],
       [27.        ],
       [30.        ],
       [22.        ],
       [29.69911765],
       [36.        ],
       [61.        ],
       [36.        ],
       [31.        ],
       [16.        ],
       [29.69911765],
       [45.5       ],
       [38.        ],
       [16.        ],
       [29.69911765],
       [29.69911765],
       [29.        ],
       [41.        ],
       [45.        ],
       [45.        ],
       [ 2.        ],
       [24.        ],
       [28.        ],
       [25.        ],
       [36.        ],
       [24.        ],
       [40.        ],
       [29.69911765],
       [ 3.        ],
       [42.        ],
       [23.        ],
       [29.69911765],
       [15.        ],
       [25.        ],
       [29.69911765],
       [28.        ],
       [22.        ],
       [38.        ],
       [29.69911765],
       [29.69911765],
       [40.        ],
       [29.        ],
       [45.        ],
       [35.        ],
       [29.69911765],
       [30.        ],
       [60.        ],
       [29.69911765],
       [29.69911765],
       [24.        ],
       [25.        ],
       [18.        ],
       [19.        ],
       [22.        ],
       [ 3.        ],
       [29.69911765],
       [22.        ],
       [27.        ],
       [20.        ],
       [19.        ],
       [42.        ],
       [ 1.        ],
       [32.        ],
       [35.        ],
       [29.69911765],
       [18.        ],
       [ 1.        ],
       [36.        ],
       [29.69911765],
       [17.        ],
       [36.        ],
       [21.        ],
       [28.        ],
       [23.        ],
       [24.        ],
       [22.        ],
       [31.        ],
       [46.        ],
       [23.        ],
       [28.        ],
       [39.        ],
       [26.        ],
       [21.        ],
       [28.        ],
       [20.        ],
       [34.        ],
       [51.        ],
       [ 3.        ],
       [21.        ],
       [29.69911765],
       [29.69911765],
       [29.69911765],
       [33.        ],
       [29.69911765],
       [44.        ],
       [29.69911765],
       [34.        ],
       [18.        ],
       [30.        ],
       [10.        ],
       [29.69911765],
       [21.        ],
       [29.        ],
       [28.        ],
       [18.        ],
       [29.69911765],
       [28.        ],
       [19.        ],
       [29.69911765],
       [32.        ],
       [28.        ],
       [29.69911765],
       [42.        ],
       [17.        ],
       [50.        ],
       [14.        ],
       [21.        ],
       [24.        ],
       [64.        ],
       [31.        ],
       [45.        ],
       [20.        ],
       [25.        ],
       [28.        ],
       [29.69911765],
       [ 4.        ],
       [13.        ],
       [34.        ],
       [ 5.        ],
       [52.        ],
       [36.        ],
       [29.69911765],
       [30.        ],
       [49.        ],
       [29.69911765],
       [29.        ],
       [65.        ],
       [29.69911765],
       [50.        ],
       [29.69911765],
       [48.        ],
       [34.        ],
       [47.        ],
       [48.        ],
       [29.69911765],
       [38.        ],
       [29.69911765],
       [56.        ],
       [29.69911765],
       [ 0.75      ],
       [29.69911765],
       [38.        ],
       [33.        ],
       [23.        ],
       [22.        ],
       [29.69911765],
       [34.        ],
       [29.        ],
       [22.        ],
       [ 2.        ],
       [ 9.        ],
       [29.69911765],
       [50.        ],
       [63.        ],
       [25.        ],
       [29.69911765],
       [35.        ],
       [58.        ],
       [30.        ],
       [ 9.        ],
       [29.69911765],
       [21.        ],
       [55.        ],
       [71.        ],
       [21.        ],
       [29.69911765],
       [54.        ],
       [29.69911765],
       [25.        ],
       [24.        ],
       [17.        ],
       [21.        ],
       [29.69911765],
       [37.        ],
       [16.        ],
       [18.        ],
       [33.        ],
       [29.69911765],
       [28.        ],
       [26.        ],
       [29.        ],
       [29.69911765],
       [36.        ],
       [54.        ],
       [24.        ],
       [47.        ],
       [34.        ],
       [29.69911765],
       [36.        ],
       [32.        ],
       [30.        ],
       [22.        ],
       [29.69911765],
       [44.        ],
       [29.69911765],
       [40.5       ],
       [50.        ],
       [29.69911765],
       [39.        ],
       [23.        ],
       [ 2.        ],
       [29.69911765],
       [17.        ],
       [29.69911765],
       [30.        ],
       [ 7.        ],
       [45.        ],
       [30.        ],
       [29.69911765],
       [22.        ],
       [36.        ],
       [ 9.        ],
       [11.        ],
       [32.        ],
       [50.        ],
       [64.        ],
       [19.        ],
       [29.69911765],
       [33.        ],
       [ 8.        ],
       [17.        ],
       [27.        ],
       [29.69911765],
       [22.        ],
       [22.        ],
       [62.        ],
       [48.        ],
       [29.69911765],
       [39.        ],
       [36.        ],
       [29.69911765],
       [40.        ],
       [28.        ],
       [29.69911765],
       [29.69911765],
       [24.        ],
       [19.        ],
       [29.        ],
       [29.69911765],
       [32.        ],
       [62.        ],
       [53.        ],
       [36.        ],
       [29.69911765],
       [16.        ],
       [19.        ],
       [34.        ],
       [39.        ],
       [29.69911765],
       [32.        ],
       [25.        ],
       [39.        ],
       [54.        ],
       [36.        ],
       [29.69911765],
       [18.        ],
       [47.        ],
       [60.        ],
       [22.        ],
       [29.69911765],
       [35.        ],
       [52.        ],
       [47.        ],
       [29.69911765],
       [37.        ],
       [36.        ],
       [29.69911765],
       [49.        ],
       [29.69911765],
       [49.        ],
       [24.        ],
       [29.69911765],
       [29.69911765],
       [44.        ],
       [35.        ],
       [36.        ],
       [30.        ],
       [27.        ],
       [22.        ],
       [40.        ],
       [39.        ],
       [29.69911765],
       [29.69911765],
       [29.69911765],
       [35.        ],
       [24.        ],
       [34.        ],
       [26.        ],
       [ 4.        ],
       [26.        ],
       [27.        ],
       [42.        ],
       [20.        ],
       [21.        ],
       [21.        ],
       [61.        ],
       [57.        ],
       [21.        ],
       [26.        ],
       [29.69911765],
       [80.        ],
       [51.        ],
       [32.        ],
       [29.69911765],
       [ 9.        ],
       [28.        ],
       [32.        ],
       [31.        ],
       [41.        ],
       [29.69911765],
       [20.        ],
       [24.        ],
       [ 2.        ],
       [29.69911765],
       [ 0.75      ],
       [48.        ],
       [19.        ],
       [56.        ],
       [29.69911765],
       [23.        ],
       [29.69911765],
       [18.        ],
       [21.        ],
       [29.69911765],
       [18.        ],
       [24.        ],
       [29.69911765],
       [32.        ],
       [23.        ],
       [58.        ],
       [50.        ],
       [40.        ],
       [47.        ],
       [36.        ],
       [20.        ],
       [32.        ],
       [25.        ],
       [29.69911765],
       [43.        ],
       [29.69911765],
       [40.        ],
       [31.        ],
       [70.        ],
       [31.        ],
       [29.69911765],
       [18.        ],
       [24.5       ],
       [18.        ],
       [43.        ],
       [36.        ],
       [29.69911765],
       [27.        ],
       [20.        ],
       [14.        ],
       [60.        ],
       [25.        ],
       [14.        ],
       [19.        ],
       [18.        ],
       [15.        ],
       [31.        ],
       [ 4.        ],
       [29.69911765],
       [25.        ],
       [60.        ],
       [52.        ],
       [44.        ],
       [29.69911765],
       [49.        ],
       [42.        ],
       [18.        ],
       [35.        ],
       [18.        ],
       [25.        ],
       [26.        ],
       [39.        ],
       [45.        ],
       [42.        ],
       [22.        ],
       [29.69911765],
       [24.        ],
       [29.69911765],
       [48.        ],
       [29.        ],
       [52.        ],
       [19.        ],
       [38.        ],
       [27.        ],
       [29.69911765],
       [33.        ],
       [ 6.        ],
       [17.        ],
       [34.        ],
       [50.        ],
       [27.        ],
       [20.        ],
       [30.        ],
       [29.69911765],
       [25.        ],
       [25.        ],
       [29.        ],
       [11.        ],
       [29.69911765],
       [23.        ],
       [23.        ],
       [28.5       ],
       [48.        ],
       [35.        ],
       [29.69911765],
       [29.69911765],
       [29.69911765],
       [36.        ],
       [21.        ],
       [24.        ],
       [31.        ],
       [70.        ],
       [16.        ],
       [30.        ],
       [19.        ],
       [31.        ],
       [ 4.        ],
       [ 6.        ],
       [33.        ],
       [23.        ],
       [48.        ],
       [ 0.67      ],
       [28.        ],
       [18.        ],
       [34.        ],
       [33.        ],
       [29.69911765],
       [41.        ],
       [20.        ],
       [36.        ],
       [16.        ],
       [51.        ],
       [29.69911765],
       [30.5       ],
       [29.69911765],
       [32.        ],
       [24.        ],
       [48.        ],
       [57.        ],
       [29.69911765],
       [54.        ],
       [18.        ],
       [29.69911765],
       [ 5.        ],
       [29.69911765],
       [43.        ],
       [13.        ],
       [17.        ],
       [29.        ],
       [29.69911765],
       [25.        ],
       [25.        ],
       [18.        ],
       [ 8.        ],
       [ 1.        ],
       [46.        ],
       [29.69911765],
       [16.        ],
       [29.69911765],
       [29.69911765],
       [25.        ],
       [39.        ],
       [49.        ],
       [31.        ],
       [30.        ],
       [30.        ],
       [34.        ],
       [31.        ],
       [11.        ],
       [ 0.42      ],
       [27.        ],
       [31.        ],
       [39.        ],
       [18.        ],
       [39.        ],
       [33.        ],
       [26.        ],
       [39.        ],
       [35.        ],
       [ 6.        ],
       [30.5       ],
       [29.69911765],
       [23.        ],
       [31.        ],
       [43.        ],
       [10.        ],
       [52.        ],
       [27.        ],
       [38.        ],
       [27.        ],
       [ 2.        ],
       [29.69911765],
       [29.69911765],
       [ 1.        ],
       [29.69911765],
       [62.        ],
       [15.        ],
       [ 0.83      ],
       [29.69911765],
       [23.        ],
       [18.        ],
       [39.        ],
       [21.        ],
       [29.69911765],
       [32.        ],
       [29.69911765],
       [20.        ],
       [16.        ],
       [30.        ],
       [34.5       ],
       [17.        ],
       [42.        ],
       [29.69911765],
       [35.        ],
       [28.        ],
       [29.69911765],
       [ 4.        ],
       [74.        ],
       [ 9.        ],
       [16.        ],
       [44.        ],
       [18.        ],
       [45.        ],
       [51.        ],
       [24.        ],
       [29.69911765],
       [41.        ],
       [21.        ],
       [48.        ],
       [29.69911765],
       [24.        ],
       [42.        ],
       [27.        ],
       [31.        ],
       [29.69911765],
       [ 4.        ],
       [26.        ],
       [47.        ],
       [33.        ],
       [47.        ],
       [28.        ],
       [15.        ],
       [20.        ],
       [19.        ],
       [29.69911765],
       [56.        ],
       [25.        ],
       [33.        ],
       [22.        ],
       [28.        ],
       [25.        ],
       [39.        ],
       [27.        ],
       [19.        ],
       [29.69911765],
       [26.        ],
       [32.        ]])

In [17]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [21]:
# 100, 791
sample_data = df.sample(100)

In [19]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [23]:
df = df.drop(sample_data.index)

In [24]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [30]:
imputer = SimpleImputer(strategy='most_frequent', add_indicator=True)
imputer.fit_transform(df[['Cabin', 'Embarked']])

array([['C23 C25 C27', 'S', True, False],
       ['C85', 'C', False, False],
       ['C23 C25 C27', 'S', True, False],
       ...,
       ['C23 C25 C27', 'S', True, False],
       ['C148', 'C', False, False],
       ['C23 C25 C27', 'Q', True, False]], shape=(791, 4), dtype=object)

In [31]:
imputer.transform(df[['Cabin', 'Embarked']])

array([['C23 C25 C27', 'S', True, False],
       ['C85', 'C', False, False],
       ['C23 C25 C27', 'S', True, False],
       ...,
       ['C23 C25 C27', 'S', True, False],
       ['C148', 'C', False, False],
       ['C23 C25 C27', 'Q', True, False]], shape=(791, 4), dtype=object)

In [32]:
imputer.statistics_

array(['C23 C25 C27', 'S'], dtype=object)

In [33]:
imputer.get_feature_names_out()

array(['Cabin', 'Embarked', 'missingindicator_Cabin',
       'missingindicator_Embarked'], dtype=object)

In [34]:
imputer.feature_names_in_

array(['Cabin', 'Embarked'], dtype=object)

In [ ]:
z_score = |(x-mean) / std| > 3

In [36]:
arr = np.array([1,2,3,4,5,90])

In [44]:
np.abs((arr - np.mean(arr)) / len(arr))

array([ 2.75      ,  2.58333333,  2.41666667,  2.25      ,  2.08333333,
       12.08333333])

In [ ]:
x - median / mad

In [ ]:
mad = np.abs(x - mean)/ n

In [45]:
np.abs((arr - np.mean(arr)) / len(arr))

array([-0.27272727,  0.64516129,  1.55172414,  2.44444444,  3.32      ,
       89.71034483])

In [57]:
def mad(arr):
    mad = np.abs((arr - np.mean(arr)) / len(arr))
    return mad

In [58]:
mad(arr)

array([ 2.75      ,  2.58333333,  2.41666667,  2.25      ,  2.08333333,
       12.08333333])

In [63]:
np.abs(arr - np.median(arr))/ mad(arr)

array([0.90909091, 0.58064516, 0.20689655, 0.22222222, 0.72      ,
       7.15862069])

In [60]:
np.median(arr)

np.float64(3.5)

In [ ]:
1 std above mean

In [68]:
m = 50000 
s = 10000
m + s

60000

In [ ]:
# 1 std 
# 2 std
# 3 extrme outler

In [69]:
# train test split 
# X_train, y_train, X_test, y_test 
from sklearn.model_selection import train_test_split

In [72]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [74]:
X = df.drop(columns=['Survived'])
y = df['Survived']

In [75]:
X.shape, y.shape

((891, 11), (891,))

In [93]:
X_train, X_test, y_train, y_test =  train_test_split(X, y, train_size=0.8, random_state=42)

In [94]:
X_train.shape, y_train.shape, X_test.shape, y_test.shape

((712, 11), (712,), (179, 11), (179,))

In [102]:
imputer = SimpleImputer(strategy='median')

In [104]:
age = imputer.fit_transform(X_train[['Age']])

In [105]:
age

array([[45.5 ],
       [23.  ],
       [32.  ],
       [26.  ],
       [ 6.  ],
       [24.  ],
       [45.  ],
       [29.  ],
       [28.  ],
       [28.  ],
       [42.  ],
       [36.  ],
       [33.  ],
       [17.  ],
       [29.  ],
       [50.  ],
       [35.  ],
       [38.  ],
       [34.  ],
       [17.  ],
       [11.  ],
       [61.  ],
       [30.  ],
       [ 7.  ],
       [63.  ],
       [20.  ],
       [28.  ],
       [29.  ],
       [36.  ],
       [28.  ],
       [50.  ],
       [27.  ],
       [30.  ],
       [33.  ],
       [28.  ],
       [28.  ],
       [ 2.  ],
       [25.  ],
       [51.  ],
       [25.  ],
       [28.  ],
       [28.  ],
       [24.  ],
       [18.  ],
       [28.  ],
       [25.  ],
       [24.  ],
       [22.  ],
       [ 0.92],
       [24.  ],
       [26.  ],
       [34.  ],
       [21.  ],
       [28.  ],
       [28.  ],
       [28.  ],
       [22.  ],
       [62.  ],
       [18.  ],
       [42.  ],
       [57.  ],
       [19.  ],
       [42.  ],
       [28.  ],
       [20.  ],
       [34.5 ],
       [28.  ],
       [28.  ],
       [23.  ],
       [22.  ],
       [52.  ],
       [30.  ],
       [36.5 ],
       [28.  ],
       [22.  ],
       [50.  ],
       [27.  ],
       [22.  ],
       [51.  ],
       [36.  ],
       [29.  ],
       [22.  ],
       [50.  ],
       [40.  ],
       [27.  ],
       [28.  ],
       [65.  ],
       [17.  ],
       [28.  ],
       [ 4.  ],
       [28.  ],
       [ 1.  ],
       [36.  ],
       [43.  ],
       [38.  ],
       [31.  ],
       [29.  ],
       [18.  ],
       [28.  ],
       [39.  ],
       [39.  ],
       [26.  ],
       [20.  ],
       [28.  ],
       [49.  ],
       [23.  ],
       [ 1.  ],
       [28.  ],
       [28.  ],
       [ 3.  ],
       [ 4.  ],
       [19.  ],
       [40.5 ],
       [ 1.  ],
       [28.  ],
       [21.  ],
       [54.  ],
       [28.  ],
       [25.  ],
       [26.  ],
       [22.  ],
       [31.  ],
       [49.  ],
       [19.  ],
       [24.  ],
       [16.  ],
       [25.  ],
       [39.  ],
       [47.  ],
       [60.  ],
       [24.  ],
       [28.  ],
       [27.  ],
       [28.  ],
       [38.  ],
       [44.  ],
       [21.  ],
       [24.  ],
       [45.  ],
       [ 8.  ],
       [ 8.  ],
       [28.  ],
       [32.  ],
       [50.  ],
       [21.  ],
       [50.  ],
       [23.  ],
       [32.  ],
       [28.  ],
       [21.  ],
       [28.  ],
       [25.  ],
       [15.  ],
       [31.  ],
       [25.  ],
       [54.  ],
       [28.  ],
       [38.  ],
       [41.  ],
       [33.  ],
       [52.  ],
       [16.  ],
       [20.  ],
       [ 9.  ],
       [28.  ],
       [28.  ],
       [28.  ],
       [54.  ],
       [26.  ],
       [60.  ],
       [28.  ],
       [44.  ],
       [20.  ],
       [28.  ],
       [16.  ],
       [43.  ],
       [17.  ],
       [37.  ],
       [62.  ],
       [ 8.  ],
       [32.  ],
       [20.  ],
       [28.  ],
       [21.  ],
       [37.  ],
       [17.  ],
       [28.  ],
       [46.  ],
       [28.  ],
       [24.  ],
       [29.  ],
       [56.  ],
       [31.  ],
       [28.  ],
       [32.  ],
       [33.  ],
       [59.  ],
       [58.  ],
       [28.  ],
       [ 3.  ],
       [28.  ],
       [16.  ],
       [45.  ],
       [43.  ],
       [30.  ],
       [28.5 ],
       [24.  ],
       [30.  ],
       [36.  ],
       [25.  ],
       [28.  ],
       [50.  ],
       [ 0.75],
       [24.  ],
       [24.  ],
       [35.  ],
       [30.  ],
       [23.  ],
       [28.  ],
       [27.  ],
       [55.  ],
       [35.  ],
       [28.  ],
       [28.  ],
       [28.  ],
       [23.  ],
       [28.  ],
       [23.  ],
       [51.  ],
       [33.  ],
       [29.  ],
       [28.  ],
       [28.  ],
       [ 2.  ],
       [14.  ],
       [54.  ],
       [15.  ],
       [22.  ],
       [27.  ],
       [28.  ],
       [28.  ],
       [28.  ],
       [39.  ],
       [ 2.  ],
       [24.  ],
       [32.  ],
       [45.5 ],
       [ 8.  ],
       [26.  ],
       [29.  ],
       [45.  ],
       [36.  ],
       [28.  ],
       [ 4.  ],
       [16.  ],
       [58.  ],
       [40.5 ],
       [25.  ],
       [28.  ],
       [51.  ],
       [28.  ],
       [17.  ],
       [28.  ],
       [40.  ],
       [25.  ],
       [47.  ],
       [28.  ],
       [44.  ],
       [23.  ],
       [18.  ],
       [29.  ],
       [12.  ],
       [11.  ],
       [22.  ],
       [19.  ],
       [22.  ],
       [33.  ],
       [56.  ],
       [ 1.  ],
       [22.  ],
       [28.  ],
       [28.  ],
       [ 7.  ],
       [ 4.  ],
       [70.5 ],
       [18.  ],
       [20.  ],
       [24.  ],
       [28.  ],
       [34.  ],
       [28.  ],
       [31.  ],
       [30.  ],
       [18.  ],
       [ 9.  ],
       [39.  ],
       [33.  ],
       [70.  ],
       [24.  ],
       [58.  ],
       [21.  ],
       [17.  ],
       [28.  ],
       [24.  ],
       [28.  ],
       [28.  ],
       [42.  ],
       [18.  ],
       [ 2.  ],
       [34.  ],
       [ 3.  ],
       [58.  ],
       [32.  ],
       [31.  ],
       [28.  ],
       [27.  ],
       [11.  ],
       [23.  ],
       [40.  ],
       [28.  ],
       [28.  ],
       [28.  ],
       [28.  ],
       [19.  ],
       [30.  ],
       [20.  ],
       [28.  ],
       [36.  ],
       [28.  ],
       [24.  ],
       [28.5 ],
       [24.  ],
       [42.  ],
       [54.  ],
       [25.  ],
       [ 7.  ],
       [25.  ],
       [27.  ],
       [24.  ],
       [28.  ],
       [28.  ],
       [19.  ],
       [22.  ],
       [28.  ],
       [28.  ],
       [42.  ],
       [50.  ],
       [ 3.  ],
       [28.  ],
       [18.  ],
       [18.  ],
       [44.  ],
       [28.  ],
       [28.  ],
       [28.  ],
       [16.  ],
       [28.  ],
       [22.  ],
       [ 4.  ],
       [28.  ],
       [24.  ],
       [30.  ],
       [29.  ],
       [24.  ],
       [45.  ],
       [32.  ],
       [21.  ],
       [35.  ],
       [28.  ],
       [28.  ],
       [36.  ],
       [41.  ],
       [23.  ],
       [34.  ],
       [28.  ],
       [28.  ],
       [15.  ],
       [28.  ],
       [18.  ],
       [30.  ],
       [32.  ],
       [ 4.  ],
       [ 2.  ],
       [28.  ],
       [28.  ],
       [48.  ],
       [31.  ],
       [47.  ],
       [26.  ],
       [ 9.  ],
       [19.  ],
       [28.  ],
       [22.  ],
       [28.  ],
       [28.  ],
       [24.  ],
       [17.  ],
       [28.  ],
       [28.  ],
       [21.  ],
       [51.  ],
       [ 3.  ],
       [ 0.75],
       [28.  ],
       [34.  ],
       [18.  ],
       [44.  ],
       [28.  ],
       [28.  ],
       [37.  ],
       [21.  ],
       [36.  ],
       [32.  ],
       [28.  ],
       [26.  ],
       [80.  ],
       [55.5 ],
       [60.  ],
       [28.  ],
       [18.  ],
       [14.5 ],
       [19.  ],
       [ 4.  ],
       [33.  ],
       [21.  ],
       [10.  ],
       [47.  ],
       [ 2.  ],
       [29.  ],
       [22.  ],
       [28.  ],
       [28.  ],
       [26.  ],
       [33.  ],
       [27.  ],
       [27.  ],
       [34.  ],
       [28.  ],
       [30.  ],
       [30.  ],
       [28.  ],
       [28.  ],
       [53.  ],
       [32.  ],
       [52.  ],
       [52.  ],
       [39.  ],
       [ 2.  ],
       [44.  ],
       [51.  ],
       [39.  ],
       [46.  ],
       [17.  ],
       [30.  ],
       [ 9.  ],
       [27.  ],
       [21.  ],
       [28.  ],
       [26.  ],
       [ 3.  ],
       [48.  ],
       [36.  ],
       [28.  ],
       [32.5 ],
       [33.  ],
       [22.  ],
       [19.  ],
       [74.  ],
       [42.  ],
       [40.  ],
       [35.  ],
       [24.  ],
       [39.  ],
       [32.5 ],
       [ 1.  ],
       [34.  ],
       [64.  ],
       [25.  ],
       [28.  ],
       [ 1.  ],
       [45.  ],
       [31.  ],
       [21.  ],
       [25.  ],
       [15.  ],
       [26.  ],
       [30.  ],
       [24.  ],
       [35.  ],
       [70.  ],
       [28.  ],
       [21.  ],
       [18.  ],
       [28.  ],
       [ 1.  ],
       [28.  ],
       [26.  ],
       [25.  ],
       [28.  ],
       [20.  ],
       [54.  ],
       [22.  ],
       [59.  ],
       [54.  ],
       [27.  ],
       [31.  ],
       [22.  ],
       [33.  ],
       [ 6.  ],
       [ 5.  ],
       [39.  ],
       [24.5 ],
       [54.  ],
       [28.  ],
       [28.  ],
       [30.  ],
       [28.  ],
       [35.  ],
       [21.  ],
       [32.  ],
       [16.  ],
       [22.  ],
       [28.  ],
       [38.  ],
       [28.  ],
       [25.  ],
       [33.  ],
       [28.  ],
       [18.  ],
       [28.  ],
       [28.  ],
       [ 2.  ],
       [ 0.42],
       [26.  ],
       [41.  ],
       [48.  ],
       [48.  ],
       [48.  ],
       [ 4.  ],
       [39.  ],
       [33.  ],
       [29.  ],
       [49.  ],
       [28.  ],
       [28.  ],
       [42.  ],
       [36.  ],
       [61.  ],
       [18.  ],
       [18.  ],
       [ 0.67],
       [32.  ],
       [28.  ],
       [28.  ],
       [28.  ],
       [16.  ],
       [31.  ],
       [48.  ],
       [22.  ],
       [13.  ],
       [32.  ],
       [28.  ],
       [46.  ],
       [28.  ],
       [42.  ],
       [35.  ],
       [ 2.  ],
       [31.  ],
       [28.  ],
       [28.  ],
       [19.  ],
       [20.  ],
       [14.  ],
       [34.  ],
       [28.  ],
       [28.  ],
       [51.  ],
       [28.  ],
       [28.  ],
       [28.  ],
       [28.  ],
       [25.  ],
       [19.  ],
       [35.  ],
       [35.  ],
       [ 9.  ],
       [20.  ],
       [42.  ],
       [30.  ],
       [28.  ],
       [21.  ],
       [47.  ],
       [25.  ],
       [16.  ],
       [45.  ],
       [38.  ],
       [56.  ],
       [28.  ],
       [31.  ],
       [30.  ],
       [28.  ],
       [14.  ],
       [16.  ],
       [40.  ],
       [55.  ],
       [19.  ],
       [45.  ],
       [36.  ],
       [27.  ],
       [49.  ],
       [41.  ],
       [19.  ],
       [33.  ],
       [27.  ],
       [28.  ],
       [35.  ],
       [29.  ],
       [30.  ],
       [34.  ],
       [29.  ],
       [19.  ],
       [35.  ],
       [28.  ],
       [40.  ],
       [62.  ],
       [25.  ],
       [26.  ],
       [18.  ],
       [34.  ],
       [48.  ],
       [28.  ],
       [24.  ],
       [17.  ],
       [38.  ],
       [28.  ],
       [40.  ],
       [22.  ],
       [ 2.  ],
       [28.  ],
       [18.  ],
       [28.  ],
       [19.  ],
       [28.  ],
       [60.  ],
       [20.  ],
       [45.  ],
       [28.  ],
       [24.  ],
       [28.  ],
       [28.  ],
       [39.  ],
       [26.  ],
       [24.  ],
       [36.  ],
       [37.  ],
       [28.  ],
       [28.  ],
       [19.  ],
       [43.  ],
       [25.  ],
       [47.  ],
       [16.  ],
       [ 0.83],
       [22.  ],
       [19.  ],
       [28.  ],
       [14.  ],
       [36.  ],
       [29.  ],
       [42.  ],
       [28.  ],
       [27.  ],
       [29.  ],
       [ 5.  ],
       [22.  ],
       [28.  ],
       [30.  ],
       [62.  ],
       [34.  ],
       [28.  ],
       [28.  ],
       [44.  ],
       [45.  ],
       [19.  ],
       [18.  ],
       [31.  ],
       [28.  ],
       [21.  ],
       [25.  ],
       [32.  ],
       [30.  ],
       [40.  ],
       [33.  ],
       [36.  ],
       [47.  ],
       [34.  ],
       [19.  ],
       [28.  ],
       [50.  ],
       [28.  ],
       [28.  ],
       [28.  ],
       [28.  ],
       [35.  ],
       [35.  ],
       [18.  ],
       [16.  ],
       [21.  ],
       [28.  ],
       [41.  ],
       [14.  ],
       [21.  ]])

In [106]:
X_train['Age'] = age

In [107]:
X_train.info()

<class 'pandas.DataFrame'>
Index: 712 entries, 331 to 102
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  712 non-null    int64
 1   Pclass       712 non-null    int64
 2   Name         712 non-null    str
 3   Sex          712 non-null    str
 4   Age          712 non-null    float64
 5   SibSp        712 non-null    int64
 6   Parch        712 non-null    int64
 7   Ticket       712 non-null    str
 8   Fare         712 non-null    float64
 9   Cabin        159 non-null    str
 10  Embarked     710 non-null    str
dtypes: float64(2), int64(4), str(5)
memory usage: 95.0 KB

In [109]:
X_test['Age'] = imputer.transform(X_test[['Age']])

In [110]:
X_test.info()

<class 'pandas.DataFrame'>
Index: 179 entries, 709 to 10
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  179 non-null    int64
 1   Pclass       179 non-null    int64
 2   Name         179 non-null    str
 3   Sex          179 non-null    str
 4   Age          179 non-null    float64
 5   SibSp        179 non-null    int64
 6   Parch        179 non-null    int64
 7   Ticket       179 non-null    str
 8   Fare         179 non-null    float64
 9   Cabin        45 non-null     str
 10  Embarked     179 non-null    str
dtypes: float64(2), int64(4), str(5)
memory usage: 24.1 KB