In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('../../Data/PlayTennis.csv')

In [3]:
df

     Outlook Temperature Humidity    Wind Play Tennis
0      Sunny         Hot     High    Weak          No
1      Sunny         Hot     High  Strong          No
2   Overcast         Hot     High    Weak         Yes
3       Rain        Mild     High    Weak         Yes
4       Rain        Cool   Normal    Weak         Yes
5       Rain        Cool   Normal  Strong          No
6   Overcast        Cool   Normal  Strong         Yes
7      Sunny        Mild     High    Weak          No
8      Sunny        Cool   Normal    Weak         Yes
9       Rain        Mild   Normal    Weak         Yes
10     Sunny        Mild   Normal  Strong         Yes
11  Overcast        Mild     High  Strong         Yes
12  Overcast         Hot   Normal    Weak         Yes
13      Rain        Mild     High  Strong          No

In [4]:
yes, no = df['Play Tennis'].value_counts()/len(df)

In [5]:
yes

0.6428571428571429

In [6]:
no

0.35714285714285715

In [7]:
entropy_tennis = -np.sum(
    (yes*(np.log2(yes)), no * (np.log2(no)))
)

In [8]:
entropy_tennis

np.float64(0.9402859586706311)

In [ ]:
# Outlook -> sunny

In [10]:
df[df['Outlook']=='Sunny']

   Outlook Temperature Humidity    Wind Play Tennis
0    Sunny         Hot     High    Weak          No
1    Sunny         Hot     High  Strong          No
7    Sunny        Mild     High    Weak          No
8    Sunny        Cool   Normal    Weak         Yes
10   Sunny        Mild   Normal  Strong         Yes

In [12]:
sunny = (- (3/5) * np.log2(3/5) ) - ( (2/5) * (np.log2(2/5) ) )

In [13]:
df[df['Outlook']=='Rain']

   Outlook Temperature Humidity    Wind Play Tennis
3     Rain        Mild     High    Weak         Yes
4     Rain        Cool   Normal    Weak         Yes
5     Rain        Cool   Normal  Strong          No
9     Rain        Mild   Normal    Weak         Yes
13    Rain        Mild     High  Strong          No

In [16]:
rain = -np.sum(((3/5) * np.log2(3/5), (2/5) * (np.log2(2/5))))

In [42]:
rain, sunny, overcast

(np.float64(0.9709505944546686), np.float64(0.9709505944546686), 0)

In [18]:
df[df['Outlook']=='Overcast']

     Outlook Temperature Humidity    Wind Play Tennis
2   Overcast         Hot     High    Weak         Yes
6   Overcast        Cool   Normal  Strong         Yes
11  Overcast        Mild     High  Strong         Yes
12  Overcast         Hot   Normal    Weak         Yes

In [19]:
4/4 * np.log2(1)

np.float64(0.0)

In [20]:
overcast = 0

In [22]:
weighted_entropy = 5/14 * sunny + 4/14 * overcast + 5/14 * rain

In [38]:
ig_outlook = entropy_tennis - weighted_entropy

In [24]:
outlook # IG

np.float64(0.24674981977443933)

In [25]:
# Temp

In [26]:
df[df['Temperature']=="Hot"]

     Outlook Temperature Humidity    Wind Play Tennis
0      Sunny         Hot     High    Weak          No
1      Sunny         Hot     High  Strong          No
2   Overcast         Hot     High    Weak         Yes
12  Overcast         Hot   Normal    Weak         Yes

In [27]:
hot = -np.sum((2/4 * np.log2(2/4), 2/4 * np.log2(2/4)))

In [28]:
hot

np.float64(1.0)

In [29]:
df[df['Temperature']=="Cool"]

    Outlook Temperature Humidity    Wind Play Tennis
4      Rain        Cool   Normal    Weak         Yes
5      Rain        Cool   Normal  Strong          No
6  Overcast        Cool   Normal  Strong         Yes
8     Sunny        Cool   Normal    Weak         Yes

In [30]:
cool = -np.sum((3/4 * np.log2(3/4), 1/4 * np.log2(1/4)))

In [31]:
cool

np.float64(0.8112781244591328)

In [32]:
df[df['Temperature']=='Mild']

     Outlook Temperature Humidity    Wind Play Tennis
3       Rain        Mild     High    Weak         Yes
7      Sunny        Mild     High    Weak          No
9       Rain        Mild   Normal    Weak         Yes
10     Sunny        Mild   Normal  Strong         Yes
11  Overcast        Mild     High  Strong         Yes
13      Rain        Mild     High  Strong          No

In [34]:
mild = -np.sum((4/6 * np.log2(4/6), 2/6 * np.log2(2/6)))

In [35]:
mild

np.float64(0.9182958340544896)

In [36]:
temp_entropy = 4/14 * hot + 4/14 * cool + 6/14 * mild

In [37]:
temp_entropy

np.float64(0.9110633930116763)

In [39]:
ig_temp = entropy_tennis - temp_entropy

In [40]:
ig_temp

np.float64(0.02922256565895487)

In [41]:
ig_outlook, ig_temp

(np.float64(0.24674981977443933), np.float64(0.02922256565895487))