In [1]:
import pandas as pd
import numpy as np

In [2]:
# pivot tables => summ. table

df = pd.DataFrame({"Name": ['A', 'B', 'C', 'A', 'B', 'C'], 
                  "Salary": np.random.randint(10000, 50000, 6)})

In [5]:
df.pivot(columns='Name')

       Salary
Name        A        B        C
0     18592.0      NaN      NaN
1         NaN  18213.0      NaN
2         NaN      NaN  48228.0
3     27634.0      NaN      NaN
4         NaN  26257.0      NaN
5         NaN      NaN  41705.0

In [9]:
df.pivot_table(columns='Name', fill_value=0, aggfunc=["mean", "count"])  #mean

           mean                   count
Name          A        B        C     A  B  C
Salary  23113.0  22235.0  44966.5     2  2  2

In [10]:
df

  Name  Salary
0    A   18592
1    B   18213
2    C   48228
3    A   27634
4    B   26257
5    C   41705

In [15]:
data

,id,name,state_id,state_code,state_name,country_id,country_code,country_name,latitude,longitude,wikiDataId
0,52,Ashkāsham,3901,BDS,Badakhshan,1,AF,Afghanistan,36.68333,71.53333,Q4805192
1,68,Fayzabad,3901,BDS,Badakhshan,1,AF,Afghanistan,37.11664,70.58002,Q156558
2,78,Jurm,3901,BDS,Badakhshan,1,AF,Afghanistan,36.86477,70.83421,Q10308323
3,84,Khandūd,3901,BDS,Badakhshan,1,AF,Afghanistan,36.95127,72.31800,Q3290334
4,115,Rāghistān,3901,BDS,Badakhshan,1,AF,Afghanistan,37.66079,70.67346,Q2670909
...,...,...,...,...,...,...,...,...,...,...,...
148056,131496,Redcliff,1957,MI,Midlands Province,247,ZW,Zimbabwe,-19.03333,29.78333,Q584001
148057,131502,Shangani,1957,MI,Midlands Province,247,ZW,Zimbabwe,-19.78333,29.36667,Q32017959
148058,131503,Shurugwi,1957,MI,Midlands Province,247,ZW,Zimbabwe,-19.67016,30.00589,Q32019023
148059,131504,Shurugwi District,1957,MI,Midlands Province,247,ZW,Zimbabwe,-19.75000,30.16667,Q7505444
148060,131508,Zvishavane District,1957,MI,Midlands Province,247,ZW,Zimbabwe,-20.30345,30.07514,Q24235929

In [11]:
data = pd.read_csv(r"D:\cities.csv")

In [16]:
data.pivot_table(columns=["name", "country_name"], index="state_name", values="state_id", fill_value=0.0)

name,'Ali Sabieh,'s Gravenmoer,'s-Gravenland,'s-Gravenzande,'s-Heerenberg,'s-Hertogenbosch,'t Hofke,'t Zand,1 Decembrie,10 de Abril,...,’Aïn Benian,’Aïn Boucif,’Aïn Deheb,’Aïn Merane,’Aïn el Bell,’Aïn el Hadjar,’Aïn el Hammam,’Aïn el Melh,’Aïn el Turk,’Elb el Jmel
country_name,Djibouti,Netherlands,Netherlands,Netherlands,Netherlands,Netherlands,Netherlands,Netherlands,Romania,Mexico,...,Algeria,Algeria,Algeria,Algeria,Algeria,Algeria,Algeria,Algeria,Algeria,Mauritania
state_name,,,,,,,,,,,,,,,,,,,,,
'Adan Governorate,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
'Amran Governorate,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
'Asir,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
A'ana,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Aargau,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Žirovnica Municipality,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Žužemberk Municipality,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Șoldănești District,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Ștefan Vodă District,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
ʻEua,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [17]:
df = pd.read_csv('data.csv')

In [18]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [27]:
df.pivot_table(columns=["Pclass", "Embarked"], index="Survived", values="Fare").T.loc[1].loc["C", 0]

np.float64(78.84198076923077)

In [36]:
pivot_ = df.pivot_table(columns=["Pclass", "Embarked"], index="Survived", values="Fare").T

In [35]:
df[(df['Pclass']==1) & (df['Embarked'] == 'C')& (df['Survived']==0)]['Fare'].mean()

np.float64(78.84198076923077)

In [35]:
df[(df['Pclass']==1) & (df['Embarked'] == 'C')& (df['Survived']==0)]['Fare'].mean()

np.float64(78.84198076923077)

In [ ]:
# pivot tables long-to-wide

In [32]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [23]:
data

Pclass             1                           2                            3  \
Embarked           C     Q          S          C      Q          S          C
Survived
0          78.841981  90.0  57.260926  25.418225  12.35  18.946591   9.878361
1         116.121754  90.0  79.750114  25.305100  12.35  21.926316  13.404668

Pclass
Embarked          Q          S
Survived
0         11.654167  14.529906
1         10.398770  15.131464

In [30]:
data.loc[0, 1]['Q']

np.float64(90.0)

In [31]:
data

Pclass             1                           2                            3  \
Embarked           C     Q          S          C      Q          S          C
Survived
0          78.841981  90.0  57.260926  25.418225  12.35  18.946591   9.878361
1         116.121754  90.0  79.750114  25.305100  12.35  21.926316  13.404668

Pclass
Embarked          Q          S
Survived
0         11.654167  14.529906
1         10.398770  15.131464

In [39]:
pivot_.T.melt() # wide-to-long

    Pclass Embarked       value
0        1        C   78.841981
1        1        C  116.121754
2        1        Q   90.000000
3        1        Q   90.000000
4        1        S   57.260926
5        1        S   79.750114
6        2        C   25.418225
7        2        C   25.305100
8        2        Q   12.350000
9        2        Q   12.350000
10       2        S   18.946591
11       2        S   21.926316
12       3        C    9.878361
13       3        C   13.404668
14       3        Q   11.654167
15       3        Q   10.398770
16       3        S   14.529906
17       3        S   15.131464

In [40]:
pivot_.T

Pclass             1                           2                            3  \
Embarked           C     Q          S          C      Q          S          C
Survived
0          78.841981  90.0  57.260926  25.418225  12.35  18.946591   9.878361
1         116.121754  90.0  79.750114  25.305100  12.35  21.926316  13.404668

Pclass
Embarked          Q          S
Survived
0         11.654167  14.529906
1         10.398770  15.131464

In [48]:
data.stack(level="Pclass").unstack()

Embarked           C                           Q                            S  \
Pclass             1          2          3     1      2          3          1
Survived
0          78.841981  25.418225   9.878361  90.0  12.35  11.654167  57.260926
1         116.121754  25.305100  13.404668  90.0  12.35  10.398770  79.750114

Embarked
Pclass            2          3
Survived
0         18.946591  14.529906
1         21.926316  15.131464

In [54]:
data.stack(level=['Pclass'])

Embarked                  C          Q          S
Survived Pclass
0        1        78.841981  90.000000  57.260926
         2        25.418225  12.350000  18.946591
         3         9.878361  11.654167  14.529906
1        1       116.121754  90.000000  79.750114
         2        25.305100  12.350000  21.926316
         3        13.404668  10.398770  15.131464

In [57]:
df['Sex'].map(lambda x: True if str(x)== 'female' else False, )

0      False
1       True
2       True
3       True
4      False
       ...
886    False
887     True
888     True
889    False
890    False
Name: Sex, Length: 891, dtype: bool

In [58]:
# time series dataset
# 'UTC' +00:00 +05:30
# 2024-10-29 12:45:32

In [66]:
import datetime
pd.to_datetime((datetime.datetime(2024, 10, 4, 4, 35)))

Timestamp('2024-10-04 04:35:00')

In [74]:
date = pd.date_range('2025-01-01', end='2025-01-30', freq='h')

In [72]:
pd.date_range('2025-01-01', end='2025-01-30', freq='h').min()

Timestamp('2025-01-01 00:00:00')

In [76]:
df = pd.DataFrame({"Date": date, 
             "Number": np.random.randint(1000, 5000, len(date))})

In [77]:
# df.to_json("date.json")

C:\Users\udaym\AppData\Local\Temp\ipykernel_2656\819057050.py:1: Pandas4Warning: The default 'epoch' date format is deprecated and will be removed in a future version, please use 'iso' date format instead.
  df.to_json("date.json")

In [79]:
pd.date_range('2025-01-01', end='2025-01-30', freq='h', tz = "Asia/Kolkata")

DatetimeIndex(['2025-01-01 00:00:00+05:30', '2025-01-01 01:00:00+05:30',
               '2025-01-01 02:00:00+05:30', '2025-01-01 03:00:00+05:30',
               '2025-01-01 04:00:00+05:30', '2025-01-01 05:00:00+05:30',
               '2025-01-01 06:00:00+05:30', '2025-01-01 07:00:00+05:30',
               '2025-01-01 08:00:00+05:30', '2025-01-01 09:00:00+05:30',
               ...
               '2025-01-29 15:00:00+05:30', '2025-01-29 16:00:00+05:30',
               '2025-01-29 17:00:00+05:30', '2025-01-29 18:00:00+05:30',
               '2025-01-29 19:00:00+05:30', '2025-01-29 20:00:00+05:30',
               '2025-01-29 21:00:00+05:30', '2025-01-29 22:00:00+05:30',
               '2025-01-29 23:00:00+05:30', '2025-01-30 00:00:00+05:30'],
              dtype='datetime64[us, Asia/Kolkata]', length=697, freq='h')

In [83]:
# us  = micro seconds
# ns = nano seconds
pd.to_datetime(df['Date'], errors="coerce") # nan nat

0     2025-01-01 00:00:00
1     2025-01-01 01:00:00
2     2025-01-01 02:00:00
3     2025-01-01 03:00:00
4     2025-01-01 04:00:00
              ...
692   2025-01-29 20:00:00
693   2025-01-29 21:00:00
694   2025-01-29 22:00:00
695   2025-01-29 23:00:00
696   2025-01-30 00:00:00
Name: Date, Length: 697, dtype: datetime64[us]

In [85]:
df['Date'].dt.date

0      2025-01-01
1      2025-01-01
2      2025-01-01
3      2025-01-01
4      2025-01-01
          ...
692    2025-01-29
693    2025-01-29
694    2025-01-29
695    2025-01-29
696    2025-01-30
Name: Date, Length: 697, dtype: object

In [86]:
df['Date'].dt.time

0      00:00:00
1      01:00:00
2      02:00:00
3      03:00:00
4      04:00:00
         ...
692    20:00:00
693    21:00:00
694    22:00:00
695    23:00:00
696    00:00:00
Name: Date, Length: 697, dtype: object

In [87]:
df['Date'].dt.day

0       1
1       1
2       1
3       1
4       1
       ..
692    29
693    29
694    29
695    29
696    30
Name: Date, Length: 697, dtype: int32

In [88]:
df['Date'].dt.month

0      1
1      1
2      1
3      1
4      1
      ..
692    1
693    1
694    1
695    1
696    1
Name: Date, Length: 697, dtype: int32

In [90]:
df.set_index('Date', inplace=True)

In [95]:
df.loc['2025-01-01']

                     Number
Date
2025-01-01 00:00:00    3625
2025-01-01 01:00:00    3704
2025-01-01 02:00:00    3732
2025-01-01 03:00:00    3890
2025-01-01 04:00:00    3657
2025-01-01 05:00:00    4899
2025-01-01 06:00:00    2735
2025-01-01 07:00:00    3430
2025-01-01 08:00:00    2581
2025-01-01 09:00:00    1795
2025-01-01 10:00:00    3317
2025-01-01 11:00:00    2461
2025-01-01 12:00:00    4323
2025-01-01 13:00:00    4764
2025-01-01 14:00:00    2997
2025-01-01 15:00:00    3959
2025-01-01 16:00:00    4832
2025-01-01 17:00:00    2370
2025-01-01 18:00:00    2214
2025-01-01 19:00:00    1057
2025-01-01 20:00:00    3389
2025-01-01 21:00:00    4296
2025-01-01 22:00:00    1636
2025-01-01 23:00:00    4252