pip install pandas

In [ ]:
# data clean
# transform
# manage

In [ ]:
import pandas as pd

In [ ]:
# Series
# DataFrames (collection of dataframe)

In [ ]:
s = pd.Series([1,2,3.5,4])

In [ ]:
df = pd.DataFrame({'A':[1,2,3,4], "B": [4,5,8,10]})

In [ ]:
s + 3

0    4.0
1    5.0
2    6.5
3    7.0
dtype: float64

In [ ]:
s / 4

0    0.250
1    0.500
2    0.875
3    1.000
dtype: float64

In [ ]:
s < 4

0     True
1     True
2     True
3    False
dtype: bool

In [ ]:
df

   A   B
0  1   4
1  2   5
2  3   8
3  4  10

In [ ]:
s.shape, df.shape

((4,), (4, 2))

In [ ]:
# load data
df = pd.read_csv("/content/sample_data/california_housing_train.csv")

In [ ]:
df

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-114.31,34.19,15.0,5612.0,1283.0,1015.0,472.0,1.4936,66900.0
1,-114.47,34.40,19.0,7650.0,1901.0,1129.0,463.0,1.8200,80100.0
2,-114.56,33.69,17.0,720.0,174.0,333.0,117.0,1.6509,85700.0
3,-114.57,33.64,14.0,1501.0,337.0,515.0,226.0,3.1917,73400.0
4,-114.57,33.57,20.0,1454.0,326.0,624.0,262.0,1.9250,65500.0
...,...,...,...,...,...,...,...,...,...
16995,-124.26,40.58,52.0,2217.0,394.0,907.0,369.0,2.3571,111400.0
16996,-124.27,40.69,36.0,2349.0,528.0,1194.0,465.0,2.5179,79000.0
16997,-124.30,41.84,17.0,2677.0,531.0,1244.0,456.0,3.0313,103600.0
16998,-124.30,41.80,19.0,2672.0,552.0,1298.0,478.0,1.9797,85800.0
16999,-124.35,40.54,52.0,1820.0,300.0,806.0,270.0,3.0147,94600.0

In [ ]:
s = pd.Series([1,2,3,4], index=["a", "b", "c", "d"], name="Series_", dtype='int64')

In [ ]:
s.name

'Series_'

In [ ]:
s.dtype

dtype('int64')

In [ ]:
type(s)
s.index

Index(['a', 'b', 'c', 'd'], dtype='object')

In [ ]:
s['a']

np.int64(1)

In [ ]:
s

a    1
b    2
c    3
d    4
Name: Series_, dtype: int64

In [ ]:
df

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-114.31,34.19,15.0,5612.0,1283.0,1015.0,472.0,1.4936,66900.0
1,-114.47,34.40,19.0,7650.0,1901.0,1129.0,463.0,1.8200,80100.0
2,-114.56,33.69,17.0,720.0,174.0,333.0,117.0,1.6509,85700.0
3,-114.57,33.64,14.0,1501.0,337.0,515.0,226.0,3.1917,73400.0
4,-114.57,33.57,20.0,1454.0,326.0,624.0,262.0,1.9250,65500.0
...,...,...,...,...,...,...,...,...,...
16995,-124.26,40.58,52.0,2217.0,394.0,907.0,369.0,2.3571,111400.0
16996,-124.27,40.69,36.0,2349.0,528.0,1194.0,465.0,2.5179,79000.0
16997,-124.30,41.84,17.0,2677.0,531.0,1244.0,456.0,3.0313,103600.0
16998,-124.30,41.80,19.0,2672.0,552.0,1298.0,478.0,1.9797,85800.0
16999,-124.35,40.54,52.0,1820.0,300.0,806.0,270.0,3.0147,94600.0

In [ ]:
df["population"].index

RangeIndex(start=0, stop=17000, step=1)

In [ ]:
df[["population", "longitude"]]

       population  longitude
0          1015.0    -114.31
1          1129.0    -114.47
2           333.0    -114.56
3           515.0    -114.57
4           624.0    -114.57
...           ...        ...
16995       907.0    -124.26
16996      1194.0    -124.27
16997      1244.0    -124.30
16998      1298.0    -124.30
16999       806.0    -124.35

[17000 rows x 2 columns]

In [ ]:
df.columns[2]

'housing_median_age'

In [ ]:
df

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-114.31,34.19,15.0,5612.0,1283.0,1015.0,472.0,1.4936,66900.0
1,-114.47,34.40,19.0,7650.0,1901.0,1129.0,463.0,1.8200,80100.0
2,-114.56,33.69,17.0,720.0,174.0,333.0,117.0,1.6509,85700.0
3,-114.57,33.64,14.0,1501.0,337.0,515.0,226.0,3.1917,73400.0
4,-114.57,33.57,20.0,1454.0,326.0,624.0,262.0,1.9250,65500.0
...,...,...,...,...,...,...,...,...,...
16995,-124.26,40.58,52.0,2217.0,394.0,907.0,369.0,2.3571,111400.0
16996,-124.27,40.69,36.0,2349.0,528.0,1194.0,465.0,2.5179,79000.0
16997,-124.30,41.84,17.0,2677.0,531.0,1244.0,456.0,3.0313,103600.0
16998,-124.30,41.80,19.0,2672.0,552.0,1298.0,478.0,1.9797,85800.0
16999,-124.35,40.54,52.0,1820.0,300.0,806.0,270.0,3.0147,94600.0

In [ ]:
s.sum()

np.int64(10)

In [ ]:
df.sum()

longitude            -2.032556e+06
latitude              6.056288e+05
housing_median_age    4.860190e+05
total_rooms           4.494230e+07
total_bedrooms        9.169984e+06
population            2.430276e+07
households            8.520773e+06
median_income         6.602083e+04
median_house_value    3.524116e+09
dtype: float64

In [ ]:
import numpy as np

In [ ]:
a = s.to_numpy()

In [ ]:
type(a)

numpy.ndarray

In [ ]:
a =a.astype(np.int8)

In [ ]:
a.itemsize # in bytes 8 bit = 1 byte

1

In [ ]:
a

array([1, 2, 3, 4], dtype=int8)

In [ ]:
a.astype("int64").dtype

dtype('int64')

In [ ]:
df

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-114.31,34.19,15.0,5612.0,1283.0,1015.0,472.0,1.4936,66900.0
1,-114.47,34.40,19.0,7650.0,1901.0,1129.0,463.0,1.8200,80100.0
2,-114.56,33.69,17.0,720.0,174.0,333.0,117.0,1.6509,85700.0
3,-114.57,33.64,14.0,1501.0,337.0,515.0,226.0,3.1917,73400.0
4,-114.57,33.57,20.0,1454.0,326.0,624.0,262.0,1.9250,65500.0
...,...,...,...,...,...,...,...,...,...
16995,-124.26,40.58,52.0,2217.0,394.0,907.0,369.0,2.3571,111400.0
16996,-124.27,40.69,36.0,2349.0,528.0,1194.0,465.0,2.5179,79000.0
16997,-124.30,41.84,17.0,2677.0,531.0,1244.0,456.0,3.0313,103600.0
16998,-124.30,41.80,19.0,2672.0,552.0,1298.0,478.0,1.9797,85800.0
16999,-124.35,40.54,52.0,1820.0,300.0,806.0,270.0,3.0147,94600.0

In [ ]:
s.astype("int32")

a    1
b    2
c    3
d    4
Name: Series_, dtype: int32

In [ ]:
df

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-114.31,34.19,15.0,5612.0,1283.0,1015.0,472.0,1.4936,66900.0
1,-114.47,34.40,19.0,7650.0,1901.0,1129.0,463.0,1.8200,80100.0
2,-114.56,33.69,17.0,720.0,174.0,333.0,117.0,1.6509,85700.0
3,-114.57,33.64,14.0,1501.0,337.0,515.0,226.0,3.1917,73400.0
4,-114.57,33.57,20.0,1454.0,326.0,624.0,262.0,1.9250,65500.0
...,...,...,...,...,...,...,...,...,...
16995,-124.26,40.58,52.0,2217.0,394.0,907.0,369.0,2.3571,111400.0
16996,-124.27,40.69,36.0,2349.0,528.0,1194.0,465.0,2.5179,79000.0
16997,-124.30,41.84,17.0,2677.0,531.0,1244.0,456.0,3.0313,103600.0
16998,-124.30,41.80,19.0,2672.0,552.0,1298.0,478.0,1.9797,85800.0
16999,-124.35,40.54,52.0,1820.0,300.0,806.0,270.0,3.0147,94600.0

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17000 entries, 0 to 16999
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   longitude           17000 non-null  float64
 1   latitude            17000 non-null  float64
 2   housing_median_age  17000 non-null  float64
 3   total_rooms         17000 non-null  float64
 4   total_bedrooms      17000 non-null  float64
 5   population          17000 non-null  float64
 6   households          17000 non-null  float64
 7   median_income       17000 non-null  float64
 8   median_house_value  17000 non-null  float64
dtypes: float64(9)
memory usage: 1.2 MB

In [ ]:
df.describe(include='all') # statistical overview

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
count,17000.000000,17000.000000,17000.000000,17000.000000,17000.000000,17000.000000,17000.000000,17000.000000,17000.000000
mean,-119.562108,35.625225,28.589353,2643.664412,539.410824,1429.573941,501.221941,3.883578,207300.912353
std,2.005166,2.137340,12.586937,2179.947071,421.499452,1147.852959,384.520841,1.908157,115983.764387
min,-124.350000,32.540000,1.000000,2.000000,1.000000,3.000000,1.000000,0.499900,14999.000000
25%,-121.790000,33.930000,18.000000,1462.000000,297.000000,790.000000,282.000000,2.566375,119400.000000
50%,-118.490000,34.250000,29.000000,2127.000000,434.000000,1167.000000,409.000000,3.544600,180400.000000
75%,-118.000000,37.720000,37.000000,3151.250000,648.250000,1721.000000,605.250000,4.767000,265000.000000
max,-114.310000,41.950000,52.000000,37937.000000,6445.000000,35682.000000,6082.000000,15.000100,500001.000000

In [ ]:
# outlier

In [ ]:
df['households']

0        472.0
1        463.0
2        117.0
3        226.0
4        262.0
         ...
16995    369.0
16996    465.0
16997    456.0
16998    478.0
16999    270.0
Name: households, Length: 17000, dtype: float64

In [ ]:
# loc, iloc
df.loc[[0, 1]] # Fancy indexing

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-114.31,34.19,15.0,5612.0,1283.0,1015.0,472.0,1.4936,66900.0
1,-114.47,34.40,19.0,7650.0,1901.0,1129.0,463.0,1.8200,80100.0

In [ ]:
df.loc[2:100, ["total_bedrooms", 'population']]

     total_bedrooms  population
2             174.0       333.0
3             337.0       515.0
4             326.0       624.0
5             236.0       671.0
6             680.0      1841.0
..              ...         ...
96            203.0       533.0
97            507.0       762.0
98            414.0      1416.0
99            274.0       862.0
100           307.0      1000.0

[99 rows x 2 columns]

In [ ]:
df.loc[0:4, -1]

KeyError: -1

In [ ]:
d = {"A": 0}
d['B']

KeyError: 'B'

In [ ]:
a[[0, 2]]

array([1, 3], dtype=int8)

In [ ]:
s['a':"c"] = 10, 10, 20

In [ ]:
s["a":"c"]

a    10
b    10
c    20
Name: Series_, dtype: int64

In [ ]:
# df = 0
data = df.copy() # shallow

In [ ]:
data[:] = df

In [ ]:
data

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-114.31,34.19,15.0,5612.0,1283.0,1015.0,472.0,1.4936,66900.0
1,-114.47,34.40,19.0,7650.0,1901.0,1129.0,463.0,1.8200,80100.0
2,-114.56,33.69,17.0,720.0,174.0,333.0,117.0,1.6509,85700.0
3,-114.57,33.64,14.0,1501.0,337.0,515.0,226.0,3.1917,73400.0
4,-114.57,33.57,20.0,1454.0,326.0,624.0,262.0,1.9250,65500.0
...,...,...,...,...,...,...,...,...,...
16995,-124.26,40.58,52.0,2217.0,394.0,907.0,369.0,2.3571,111400.0
16996,-124.27,40.69,36.0,2349.0,528.0,1194.0,465.0,2.5179,79000.0
16997,-124.30,41.84,17.0,2677.0,531.0,1244.0,456.0,3.0313,103600.0
16998,-124.30,41.80,19.0,2672.0,552.0,1298.0,478.0,1.9797,85800.0
16999,-124.35,40.54,52.0,1820.0,300.0,806.0,270.0,3.0147,94600.0

In [ ]:
df

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-114.31,34.19,15.0,5612.0,1283.0,1015.0,472.0,1.4936,66900.0
1,-114.47,34.40,19.0,7650.0,1901.0,1129.0,463.0,1.8200,80100.0
2,-114.56,33.69,17.0,720.0,174.0,333.0,117.0,1.6509,85700.0
3,-114.57,33.64,14.0,1501.0,337.0,515.0,226.0,3.1917,73400.0
4,-114.57,33.57,20.0,1454.0,326.0,624.0,262.0,1.9250,65500.0
...,...,...,...,...,...,...,...,...,...
16995,-124.26,40.58,52.0,2217.0,394.0,907.0,369.0,2.3571,111400.0
16996,-124.27,40.69,36.0,2349.0,528.0,1194.0,465.0,2.5179,79000.0
16997,-124.30,41.84,17.0,2677.0,531.0,1244.0,456.0,3.0313,103600.0
16998,-124.30,41.80,19.0,2672.0,552.0,1298.0,478.0,1.9797,85800.0
16999,-124.35,40.54,52.0,1820.0,300.0,806.0,270.0,3.0147,94600.0

In [ ]:
# head, tail, sample
df.head(10) # top 5 rows

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-114.31,34.19,15.0,5612.0,1283.0,1015.0,472.0,1.4936,66900.0
1,-114.47,34.40,19.0,7650.0,1901.0,1129.0,463.0,1.8200,80100.0
2,-114.56,33.69,17.0,720.0,174.0,333.0,117.0,1.6509,85700.0
3,-114.57,33.64,14.0,1501.0,337.0,515.0,226.0,3.1917,73400.0
4,-114.57,33.57,20.0,1454.0,326.0,624.0,262.0,1.9250,65500.0
5,-114.58,33.63,29.0,1387.0,236.0,671.0,239.0,3.3438,74000.0
6,-114.58,33.61,25.0,2907.0,680.0,1841.0,633.0,2.6768,82400.0
7,-114.59,34.83,41.0,812.0,168.0,375.0,158.0,1.7083,48500.0
8,-114.59,33.61,34.0,4789.0,1175.0,3134.0,1056.0,2.1782,58400.0
9,-114.60,34.83,46.0,1497.0,309.0,787.0,271.0,2.1908,48100.0

In [ ]:
df.tail(30) # bottom 5

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
16970,-124.17,40.80,52.0,1606.0,419.0,891.0,367.0,1.5850,75500.0
16971,-124.17,40.80,52.0,1557.0,344.0,758.0,319.0,1.8529,62500.0
16972,-124.17,40.79,43.0,2285.0,479.0,1169.0,482.0,1.9688,70500.0
16973,-124.17,40.78,39.0,1606.0,330.0,731.0,327.0,1.6369,68300.0
16974,-124.17,40.77,30.0,1895.0,366.0,990.0,359.0,2.2227,81300.0
16975,-124.17,40.76,26.0,1776.0,361.0,992.0,380.0,2.8056,82800.0
16976,-124.17,40.75,13.0,2171.0,339.0,951.0,353.0,4.8516,116100.0
16977,-124.17,40.62,32.0,1595.0,309.0,706.0,277.0,2.8958,86400.0
16978,-124.18,40.79,39.0,1836.0,352.0,883.0,337.0,1.7450,70500.0
16979,-124.18,40.78,37.0,1453.0,293.0,867.0,310.0,2.5536,70200.0
16980,-124.18,40.78,34.0,1592.0,364.0,950.0,317.0,2.1607,67000.0
16981,-124.18,40.78,33.0,1076.0,222.0,656.0,236.0,2.5096,72200.0
16982,-124.18,40.62,35.0,952.0,178.0,480.0,179.0,3.0536,107000.0
16983,-124.19,41.78,15.0,3140.0,714.0,1645.0,640.0,1.6654,74600.0
16984,-124.19,40.78,37.0,1371.0,319.0,640.0,260.0,1.8242,70000.0
16985,-124.19,40.77,30.0,2975.0,634.0,1367.0,583.0,2.4420,69000.0
16986,-124.19,40.73,21.0,5694.0,1056.0,2907.0,972.0,3.5363,90100.0
16987,-124.21,41.77,17.0,3461.0,722.0,1947.0,647.0,2.5795,68400.0
16988,-124.21,41.75,20.0,3810.0,787.0,1993.0,721.0,2.0074,66900.0
16989,-124.21,40.75,32.0,1218.0,331.0,620.0,268.0,1.6528,58100.0
16990,-124.22,41.73,28.0,3003.0,699.0,1530.0,653.0,1.7038,78300.0
16991,-124.23,41.75,11.0,3159.0,616.0,1343.0,479.0,2.4805,73200.0
16992,-124.23,40.81,52.0,1112.0,209.0,544.0,172.0,3.3462,50800.0
16993,-124.23,40.54,52.0,2694.0,453.0,1152.0,435.0,3.0806,106700.0
16994,-124.25,40.28,32.0,1430.0,419.0,434.0,187.0,1.9417,76100.0
16995,-124.26,40.58,52.0,2217.0,394.0,907.0,369.0,2.3571,111400.0
16996,-124.27,40.69,36.0,2349.0,528.0,1194.0,465.0,2.5179,79000.0
16997,-124.30,41.84,17.0,2677.0,531.0,1244.0,456.0,3.0313,103600.0
16998,-124.30,41.80,19.0,2672.0,552.0,1298.0,478.0,1.9797,85800.0
16999,-124.35,40.54,52.0,1820.0,300.0,806.0,270.0,3.0147,94600.0

In [ ]:
df.sample(20) # random 1 row

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
5735,-118.19,34.04,40.0,1095.0,305.0,1322.0,281.0,1.9688,150000.0
14709,-122.19,38.09,8.0,614.0,118.0,278.0,115.0,6.3735,166300.0
13979,-122.04,37.66,10.0,2031.0,357.0,867.0,352.0,5.3169,299200.0
12146,-121.44,36.84,7.0,1644.0,338.0,1143.0,331.0,4.0050,180400.0
13583,-121.97,37.01,21.0,2073.0,357.0,1044.0,351.0,4.5682,371600.0
2950,-117.77,33.70,3.0,3636.0,749.0,1486.0,696.0,5.5464,207500.0
16705,-122.83,38.89,11.0,640.0,134.0,268.0,90.0,3.4514,100000.0
523,-117.00,32.85,24.0,1888.0,319.0,950.0,319.0,5.2820,140800.0
14902,-122.23,38.10,47.0,1303.0,278.0,694.0,269.0,2.5969,92800.0
2949,-117.77,33.70,4.0,2446.0,622.0,1315.0,560.0,3.7147,137500.0
3961,-117.96,33.82,29.0,2176.0,468.0,1632.0,428.0,3.7070,180400.0
4376,-118.02,33.90,34.0,1636.0,358.0,977.0,357.0,3.5938,209900.0
13066,-121.87,37.35,52.0,1557.0,424.0,1580.0,434.0,2.3277,183700.0
5244,-118.14,34.15,41.0,1256.0,407.0,855.0,383.0,1.9923,500001.0
2960,-117.77,33.53,32.0,3116.0,661.0,1105.0,543.0,5.1837,445600.0
15985,-122.44,37.79,52.0,2083.0,491.0,1224.0,483.0,4.0882,468800.0
6756,-118.29,33.84,23.0,3626.0,799.0,2321.0,731.0,4.7393,237900.0
12080,-121.43,38.65,18.0,909.0,198.0,661.0,176.0,3.1696,77400.0
3278,-117.86,33.62,23.0,3166.0,411.0,1092.0,345.0,7.9367,500001.0
4035,-117.97,33.86,34.0,2138.0,490.0,1682.0,463.0,3.6006,161700.0

In [ ]:
8