In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.DataFrame({
    "Name": ['A', 'B', 'C', 'A', 'B', 'C'],
    'Age': [20, 22, 40, 50, 36, 20]
})

Senior > 40 |
40 <= mid < 30|
30 <= junior|

In [3]:
df  # "Seniority" senior > 40, mid> 30, junior< 30

  Name  Age
0    A   20
1    B   22
2    C   40
3    A   50
4    B   36
5    C   20

In [6]:
df["Seniority"] = df['Age'].apply(lambda x: 'senior'  if x > 40 else 'mid'  if x > 30 else 'junior')

In [7]:
df

  Name  Age Seniority
0    A   20    junior
1    B   22    junior
2    C   40       mid
3    A   50    senior
4    B   36       mid
5    C   20    junior

In [18]:
# df.assign(exp= lambda x: 'high' if x['Seniority'] == 'senior' else 'low')
def check_exp(x):
    if x == 'senior':
        return 'high'
    else:
        return 'low'

In [20]:
df['Seniority'].apply(check_exp)

0     low
1     low
2     low
3    high
4     low
5     low
Name: Seniority, dtype: str

In [9]:
df['one'] = 1

In [25]:
df = df.assign(add = lambda x: x['Age']+ x['one']) # what is *args and **kw args

In [26]:
# windows function
df

  Name  Age Seniority  one  add
0    A   20    junior    1   21
1    B   22    junior    1   23
2    C   40       mid    1   41
3    A   50    senior    1   51
4    B   36       mid    1   37
5    C   20    junior    1   21

In [28]:
np.array([np.nan, 2, 1]).mean()

np.float64(nan)

In [ ]:
# 1,2,3,4
# 1 
# 1+2
# 1+2+3
# 1+2+3+4

In [30]:
data = pd.DataFrame({"number": np.arange(1, 11)})

In [37]:
data['rolling'] = data['number'].rolling(window=5, min_periods=2).mean()

In [40]:
data['number'].expanding().sum()

0     1.0
1     3.0
2     6.0
3    10.0
4    15.0
5    21.0
6    28.0
7    36.0
8    45.0
9    55.0
Name: number, dtype: float64

In [45]:
# groupby filter 
df.groupby('Seniority')['Age'].mean()

Seniority
junior    20.666667
mid       38.000000
senior    50.000000
Name: Age, dtype: float64

In [48]:
df.groupby('Seniority').filter(lambda x: x['Age'].mean() >30)

  Name  Age Seniority  one  add
2    C   40       mid    1   41
3    A   50    senior    1   51
4    B   36       mid    1   37

In [ ]:
# whitespace normalize
# case normalize
# remove punc. .,
def clean_(s: str)
s = "hello world                   Thi s.is_____python. AND WE ARE LEARNING it...."