In [1]:
import numpy as np
import pandas as pd

In [23]:
df = pd.DataFrame({"Numbers": [1,2,3,4,5,np.nan, 6,7,8,2, pd.NA]})

In [24]:
df['Numbers'].dtype

dtype('O')

In [25]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 11 entries, 0 to 10
Data columns (total 1 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Numbers  9 non-null      object
dtypes: object(1)
memory usage: 220.0+ bytes

In [26]:
df['Numbers'].astype(np.int64)

ValueError: cannot convert float NaN to integer

In [ ]:
#numpy, np.int64 # nan, na 
#pandas # np.nan, pd.NA 
df['Numbers'].astype("Int64") # converts np.nan to NA

In [27]:
# nullable datatypes
# Int64, Int32, Int16
# Float32,

# np nan NA 
pd.Int16Dtype()
pd.Int32Dtype()
pd.Int64Dtype()

Int64Dtype()

In [28]:
df['Numbers'] = df['Numbers'].astype(pd.Int8Dtype())

In [29]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 11 entries, 0 to 10
Data columns (total 1 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Numbers  9 non-null      Int8
dtypes: Int8(1)
memory usage: 154.0 bytes

In [33]:
df[df.duplicated()]

    Numbers
9         2
10     <NA>

In [34]:
df.drop_duplicates()

   Numbers
0        1
1        2
2        3
3        4
4        5
5     <NA>
6        6
7        7
8        8

In [35]:
df.duplicated()

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9      True
10     True
dtype: bool

In [36]:
df

    Numbers
0         1
1         2
2         3
3         4
4         5
5      <NA>
6         6
7         7
8         8
9         2
10     <NA>

In [57]:
s = "Hello World 123"
# for i in s:
#     print(i)
s.split() # " "

['Hello', 'World', '123']

In [40]:
df = pd.read_csv("../../Data/train.csv")

In [60]:
df['Name'].str.lower()

0                                braund, mr. owen harris
1      cumings, mrs. john bradley (florence briggs th...
2                                 heikkinen, miss. laina
3           futrelle, mrs. jacques heath (lily may peel)
4                               allen, mr. william henry
                             ...
886                                montvila, rev. juozas
887                         graham, miss. margaret edith
888             johnston, miss. catherine helen "carrie"
889                                behr, mr. karl howell
890                                  dooley, mr. patrick
Name: Name, Length: 891, dtype: str

In [63]:
df['Name'].str.casefold()

0                                braund, mr. owen harris
1      cumings, mrs. john bradley (florence briggs th...
2                                 heikkinen, miss. laina
3           futrelle, mrs. jacques heath (lily may peel)
4                               allen, mr. william henry
                             ...
886                                montvila, rev. juozas
887                         graham, miss. margaret edith
888             johnston, miss. catherine helen "carrie"
889                                behr, mr. karl howell
890                                  dooley, mr. patrick
Name: Name, Length: 891, dtype: str

In [53]:
# type(pd.DataFrame({"Numbers": [1,2,3,4,[1,2,3]]})['Numbers'].astype("string")[4])

str

In [58]:
s.title()

'Hello World 123'

In [59]:
s.capitalize()

'Hello world 123'

In [64]:
s = "       He      l     lo      Wor     ld       " # HelloWorld 
s.replace(" ", '')

'HelloWorld'

In [66]:
s.split()

['He', 'l', 'lo', 'Wor', 'ld']

In [74]:
"".join(s.split())

'HelloWorld'

In [80]:
s = 'Hello,Wor"l"d.'

In [96]:
def clean_sp_chr(s: str) -> str:
    res = ''
    for i in s:
        if i in (',.()""'):
            continue
        # res += "".join(i)
        res = res + "".join(i)
    return res

In [86]:
clean_sp_chr(s)

'HelloWorld'

In [89]:
for i in range(10):
    if i == 2:
        continue
        print(i)

In [91]:
"".join("H")

'H'

In [97]:
df['Name'].apply(clean_sp_chr)

0                                Braund Mr Owen Harris
1      Cumings Mrs John Bradley Florence Briggs Thayer
2                                 Heikkinen Miss Laina
3             Futrelle Mrs Jacques Heath Lily May Peel
4                               Allen Mr William Henry
                            ...
886                                Montvila Rev Juozas
887                         Graham Miss Margaret Edith
888               Johnston Miss Catherine Helen Carrie
889                                Behr Mr Karl Howell
890                                  Dooley Mr Patrick
Name: Name, Length: 891, dtype: str

In [102]:
# lambda functions 
# single line functions
func = lambda x: "True" if x > 10 else "False"

In [104]:
func(120)

'True'

In [107]:
"True" if 2< 3 else "False"

'True'

In [110]:
# value_if_true condition value_if_false 
0 if x == 'male' else 1
# lambda vars: function_define 
df['Name'].str.split(expand=True)

,0,1,2,3,4,5,6,7,8,9,10,11,12,13
0,"Braund,",Mr.,Owen,Harris,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,"Cumings,",Mrs.,John,Bradley,(Florence,Briggs,Thayer),NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,"Heikkinen,",Miss.,Laina,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,"Futrelle,",Mrs.,Jacques,Heath,(Lily,May,Peel),NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,"Allen,",Mr.,William,Henry,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,"Montvila,",Rev.,Juozas,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
887,"Graham,",Miss.,Margaret,Edith,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
888,"Johnston,",Miss.,Catherine,Helen,"""Carrie""",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
889,"Behr,",Mr.,Karl,Howell,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
890,"Dooley,",Mr.,Patrick,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [119]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [ ]:
df['Sex'].apply(lambda x:  0 str(x)) # male = 0 and female = 1

In [121]:
%ls

 Volume in drive E is DRIVE
 Volume Serial Number is EBC5-C7F0

 Directory of E:\class_repos\DataScience_evening\notebooks\pandas

2026-03-17  06:59 PM    <DIR>          .
2026-03-17  05:40 PM    <DIR>          ..
2026-03-17  05:41 PM    <DIR>          .ipynb_checkpoints
2026-03-17  06:59 PM            56,609 Untitled.ipynb
               1 File(s)         56,609 bytes
               3 Dir(s)  74,220,670,976 bytes free

In [127]:
df.to_csv('../../Data/data.csv', index=False)

In [125]:
pd.read_csv('data.csv')

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [129]:
df.to_excel("data.xlsx")

ArrowKeyError: No type extension with name arrow.py_extension_type found